### ISSUE TITLE
Close philkra's repository in favor of nipwaayoni

### ISSUE THREAD

**Issue by tsantos84** [nipwaayoni/elastic-apm-php-agent#27]
Is there a plan when developers should start using this repository instead of the old one? I think we'd signal the old one as a closed and encourage developers to use nipwaayoni. WDYT?

**Comment by dstepe** [comment]
I agree. I want to get a non beta/rc release done before recommending developers switch. I've been poking on issues and PRs in the philkra project (and for the Laravel package) encouraging people to try these and provide feedback. It's only been a couple of days, though. I'm starting build these pre-release versions into some work I'm doing and so far it's quite promising.

I do hope to get PR #14 merged as well. That has potential impact on usage and I'd rather not have to ask people to deal with that later. The change will make testing of the Agent behavior with sending the HTTP request much easier, and that's important to me. There is a conflict which I think I can work around and get that merged today.

I'd like to have some positive feedback on the candidate for release rather than just relying on my experience. If you and others could post your experience, I'd more confident in making a release soon.

**Comment by tsantos84** [comment]
Hi @dstepe , I could test this but probably not on the time you need to validate the RC. :(

**Comment by dstepe** [comment]
I understand. We do what we can. I've been doing a bit with and feel it's in a good place. I have another volunteer who I hope will join and test as well.

I sent you an invitation to the Nipwaayoni org if you are interested. That would allow you to participate directly in reviews and development. If that's not a good fit for you right now, disregard and continue working as you can through issues and PRs.

**Comment by tsantos84** [comment]
I've just accepted the invitation. Thanks, btw. I'm very interested to participate on this project and have lot of ideas we could discuss. I have some experience written Symfony Bundles and this could be a new package to have in this organisation.

**Comment by tsantos84** [comment]
Another thing we could have is concrete spans (eg. DatabaseSpan, HttpRequestSpan, FilesystemSpan and etc). Having a contract more expressive easily the capture of metrics and fits better when add them to Laravel or Symfony, for example.

**Comment by tsantos84** [comment]
And finally, what about to bump PHP version to 7.4 and add typed properties to classes? 

Sorry for the spam. :)

**Comment by dstepe** [comment]
The Symfony bundle sounds good. I'm very in favor of concrete classes to represent as many entities as possible.

As much as I would like to set the minimum version to PHP 7.4, but I think it's too early. My org is still primarily on 7.3 and I'm sure others are in that situation. Once we get a stable release, I'd like to put a roadmap together. Maybe we look at some of these big changes for 8.0 and start laying the ground work now.

**Comment by tsantos84** [comment]
> The Symfony bundle sounds good. I'm very in favor of concrete classes to represent as many entities as possible.

Let's discuss about these two topics then.

> As much as I would like to set the minimum version to PHP 7.4, but I think it's too early. My org is still primarily on 7.3 and I'm sure others are in that situation. Once we get a stable release, I'd like to put a roadmap together. Maybe we look at some of these big changes for 8.0 and start laying the ground work now.

Agreed.
